package axi4_pkg;
import axi4_enum_pkg::*;

parameter DATA_WIDTH   = 32         ;
parameter ADDR_WIDTH   = 16         ;
parameter MEMORY_DEPTH = 1024       ;
parameter MAX_ADDR     = 4095       ;   //maximum adderess write or read address can access
parameter MAX_aligned_addr = 4092   ;   //maximum aligned address write or read address can access
parameter MAX_ADDR_IN  = 16'hFFFF   ;   //maximum address that can be generated by the randomization of the address signal
localparam MAX_WAIT_CYCLES = 10     ;

    //struct used to store the address data type and burst length for write trns to be used in driving the read transactions
  typedef  struct {
        logic [ADDR_WIDTH-1:0] addr;
        logic [7:0]            len ;
    } prev_written_addr;

    //struct used for countering the number of correct and wrong transactions for each test case to be used in the report generation at the end of the simulation
    typedef struct {
    int correct_cnt;
    int error_cnt;
    int transactions;
} test_stats_t;

test_stats_t stats[axi_test_e];

class axi4_pkt;

   bit                            ACLK       ;
   rand bit                       ARESETn    ;

    // Write address channel
   rand logic [ADDR_WIDTH-1:0]    AWADDR     ;
   rand logic [7:0]               AWLEN      ;
   rand logic [2:0]               AWSIZE     ;
   rand logic                     AWVALID    ;
   logic                          AWREADY    ;

    // Write data channel
   rand logic  [DATA_WIDTH-1:0]    WDATA      ;
   rand logic                      WVALID     ;
   rand logic                      WLAST      ;
   logic                           WREADY     ;

    // Write response channel
   logic  [1:0]                    BRESP      ;
   logic                           BVALID     ;
   rand logic                      BREADY     ;

    // Read address channel
   rand logic  [ADDR_WIDTH-1:0]    ARADDR     ;
   rand logic  [7:0]               ARLEN      ;
   rand logic  [2:0]               ARSIZE     ;
   rand logic                      ARVALID    ;
   logic                           ARREADY    ;

    // Read data channel
   logic  [DATA_WIDTH-1:0]         RDATA      ;
   logic  [1:0]                    RRESP      ;
   logic                           RVALID     ;
   logic                           RLAST      ;
   rand logic                      RREADY     ;


   //Test cases to be randomized 
   axi_test_e test_cases                             ;
   rand axi_test_e test_cases_read                   ;
   rand axi_test_e test_cases_write                  ;

   //queue to store data for burst transactions 
    rand logic [DATA_WIDTH-1:0] data_queue [$]  ;

    //queue to send WVALID that can take values 0 or 1 for every beat
    rand logic WVALID_queue [$]                 ; //each bit WVALID is corresponding to each beat on the WDATA bus
    logic WVALID_queue_mon [$]                  ; //queue to store WVALID values for monitoring

    rand logic BREADY_queue [$]                 ; //each bit BREADY is corresponding to each beat on the BRESP bus

    //queue to store RREADY values for burst transactions " I wanna handle during the test that RREADY can take multiple values during reads and how the dut will respond"
    rand logic RREADY_queue [$]                 ; //each bit RREADY is corresponding to each beat on the RRDATA bus
    logic RREADY_queue_mon [$]                  ; //queue to store RREADY values for monitoring

    //ARLEN_constr used for the RREADY constraint 
    logic [7:0] ARLEN_constr =0; 


    //*******************************************
    //              Constraints
    //*******************************************

    // test constraint
    constraint test_cases_ct {
        test_cases_write inside {AXI_MAX_MIN_ADDR_WRITE, AXI_BURST_WRITE, AXI_ERR_INJECTRION_WRITE  };
        test_cases_read  inside {AXI_MAX_MIN_ADDR_READ , AXI_BURST_READ , AXI_ERR_INJECTION_READ    };
       if(test_cases_write == AXI_MAX_MIN_ADDR_WRITE)
            test_cases_read == AXI_MAX_MIN_ADDR_READ;

        else if(test_cases_write == AXI_BURST_WRITE)
            test_cases_read == AXI_BURST_READ;

        else if(test_cases_write == AXI_ERR_INJECTRION_WRITE)
            test_cases_read == AXI_ERR_INJECTION_READ;
    }
    
    //reset constraint to be off most of the time
    constraint ARESETn_ct { ARESETn dist {1:/90, 0:/10};}

    //write address to be within the memory boundary limit with a distribution given to the corner adderesses 
    constraint AWADDR_ct  { 
                            
        // AWADDR dist   {0:/20, MAX_ADDR:/20, [ 0+1 : MAX_ADDR-1] :/60} ;
        AWADDR == int'(AWADDR /  (2**AWSIZE) ) * (2**AWSIZE) ; // Ensure AWADDR is aligned to the beat size

        if(test_cases == AXI_MAX_MIN_ADDR_WRITE) 
            AWADDR dist {0:/50, MAX_aligned_addr:/50} ; //el mushkla hena ////////////////////////////////////
        else if (test_cases == AXI_ERR_INJECTRION_WRITE){
            //   ! AWADDR inside {[0:MAX_aligned_addr]}  ;  
             AWADDR inside {[0:$]}  ;  
            //   AWADDR dist { [MAX_aligned_addr+1 : MAX_aligned_addr + 1000] := 50, [MAX_aligned_addr + 1001 : MAX_ADDR_IN] := 50};
        }   
        else
         AWADDR inside {[0:MAX_ADDR]}    ;
    }   

   //number of beats should be constrainted such that not to exceed the memory boundary in all cases except the error injection test case
    constraint AWLEN_ct {
    solve AWADDR before AWLEN       ;

        if(test_cases == AXI_ERR_INJECTRION_WRITE || test_cases == AXI_ERR_INJECTION_READ) 
            (((AWLEN + 1) * (2**AWSIZE)) - 1) + AWADDR  > 4095   ;
        else
            (((AWLEN + 1) * (2**AWSIZE)) - 1) + AWADDR <= 4095   ;
   }

   //our design doesn't support concurrent transmission, so we need to ensure that AWVALID != ARVALID
   constraint AWVALID_ct{
   AWVALID dist {1:/60, 0:/20};
   AWVALID == 1 -> ARVALID == 0;
   }

   //most of the WVALID is high 
   constraint WVALID_ct { WVALID dist {1:/80, 0:/20};}

   
   //most of the WVALID is high 
constraint WVALID_queue_ct {
    // Use a fixed size to eliminate any ambiguity
    WVALID_queue.size() == AWLEN + 10;

    foreach (WVALID_queue[i]) {
        // Randomize each entry
        WVALID_queue[i] dist {1 := 90, 0 := 10};

        // Only access i+1 when it is within bounds
        if (i < WVALID_queue.size()-1) {
            if (WVALID_queue[i] == 0)
                WVALID_queue[i+1] == 1;
    }
    }

    // Ensure the last entry is valid
    WVALID_queue[WVALID_queue.size()-1] == 1;
}

constraint BREADY_ct {
    BREADY_queue.size() == AWLEN + 1000;
        foreach (WVALID_queue[i]) {
        // Randomize each entry
        WVALID_queue[i] dist {1 := 90, 0 := 10};

        }
}

   //AWSIZE should be constrained to 2 where number of bytes per beat = 2^AWSIZE and our memory width is 32 bits = 4 bytes
    constraint ASIZE_ct{ AWSIZE == 2;}

//    //Constraint for the write address to take all zeros, all ones, alternating patterns
//     constraint WDATA_ct {
//         WDATA dist {0 :/ 15, 'hFFFF_FFFF :/ 15, 'h5555_5555 :/15 , 'hAAAA_AAAA :/15, [0:$] :/40};}

constraint data_queue_ct {
    // Match sizes exactly
    data_queue.size() == WVALID_queue.size();

    foreach (data_queue[i]) {
        data_queue[i] dist {
            32'h0000_0000 :/ 10,
            32'hFFFF_FFFF :/ 10,
            32'h5555_5555 :/ 10,
            32'hAAAA_AAAA :/ 10,
            [0:$]        :/ 60
        };
    }
}
   // Read address within memory boundary with same distribution
    constraint ARADDR_ct  { 
        ARADDR inside {[0:MAX_ADDR]}                                  ;
        // ARADDR dist   {0:/20, MAX_ADDR:/20, [0+1 : MAX_ADDR-1] :/60}  ;
        ARADDR == int'(ARADDR /  (2**ARSIZE) ) * (2**ARSIZE) ; // Ensure ARADDR is aligned to the beat size
        if(test_cases == AXI_MAX_MIN_ADDR_READ) 
            ARADDR dist {0:/50, MAX_aligned_addr:/50} ;
        else if (test_cases == AXI_ERR_INJECTION_READ)
              ! ARADDR inside {[0:MAX_aligned_addr]}  ;  
        }   


   //most of the RREADY is high 
constraint RREADY_queue_ct {
    // Use a fixed size to eliminate any ambiguity
    RREADY_queue.size() == 1000;

    foreach (RREADY_queue[i]) {
        // Randomize each entry
        RREADY_queue[i] dist {1 := 90, 0 := 10};

        // Only access i+1 when it is within bounds
        if (i < RREADY_queue.size()-1)  {
            if (RREADY_queue[i] == 0)
                RREADY_queue[i+1] == 1; }
    }

    // Ensure the last entry is valid
    // RREADY_queue[RREADY_queue.size()-1] == 1;
}

   // Number of read beats constrained against 4KB boundary
    constraint ARLEN_ct {
        // solve ARADDR before ARLEN;

        if (test_cases == AXI_ERR_INJECTRION_WRITE || test_cases == AXI_ERR_INJECTION_READ) 
           ((ARLEN + 1) * (2**ARSIZE)) + ARADDR  > 4095;
        else
            ((ARLEN + 1) * (2**ARSIZE)) + ARADDR <= 4095;
    }

    constraint ARVALID_ct{
   ARVALID dist {1:/60, 0:/20};
   ARVALID == 1 -> AWVALID == 0;
   }

   // ARSIZE aligned with memory width (32-bit = 4 bytes)
    constraint ARSIZE_ct { 
        ARSIZE == 2; 
    }

    //****************Covergroups****************
    covergroup ax_cg ;
       option.per_instance   = 1; 
     type_option.merge_instances = 1; 
    ARESETn_cp: coverpoint ARESETn {
        bins zeros = {0}            ;
        bins ones  = {1}            ;
        bins trans = (1 => 0 => 1)  ;
    }


    AWADDR_legal_cp: coverpoint AWADDR iff(AWVALID && ARESETn) {
        bins AWADDR_min            = {0}                   ;
        bins AWADDR_max            = {MAX_aligned_addr}            ;
        bins AWADDR_range          = {[0+1:MAX_aligned_addr-1]}    ;
        illegal_bins invalid_range = {[MAX_aligned_addr +1:$]}     ;
    }

    AWLEN_cp: coverpoint AWLEN iff(AWVALID && ARESETn) {
        bins AWLEN_min_range       = {[0:64]}   ;
        bins AWLEN_mid_range       = {[65:128]} ;
        bins AWLEN_max_range       = {[129:$]}  ; 
    }

    AWREADY_cp: coverpoint AWREADY {
        bins ready = {1} ;
    }


     WVALID: coverpoint WVALID {
        bins valid = {1} ;
        bins not_valid = {0} ;
    }

     BREADY: coverpoint BREADY {
        bins ready = {1} ;
        bins not_ready = {0} ;
    }
    
     ARREADY_cp: coverpoint ARREADY {
        bins ready = {1} ;
        ignore_bins not_ready = {0} ;
    }


     RREADY: coverpoint RREADY {
        bins ready = {1} ;
        bins not_ready = {0} ;
    }

    AWSIZE_cp: coverpoint AWSIZE iff(AWVALID && ARESETn) {
        bins AWSIZE_4byte = {2}; 
    }
                                                                        
    WDATA_cp: coverpoint WDATA iff(WVALID && ARESETn) {
        bins all_zeros = {0}                                       ;
        bins all_ones  = {{DATA_WIDTH{1'b1}}}                      ;
        bins alternating_pattern[] = { 'h5555_5555, 'hAAAA_AAAA }  ;
        bins misc      = default                                   ;
    }

    BRESP_cp: coverpoint BRESP {
        bins OKAY   = {2'b00}   ;
        illegal_bins SLVERR = {2'b10}   ;
    }

    ARADDR_legal_cp: coverpoint ARADDR iff(ARVALID && ARESETn){
        bins ARADDR_min            = {0}                   ;
        bins ARADDR_max            = {MAX_aligned_addr}            ;
        bins ARADDR_range          = {[0+1:MAX_aligned_addr-1]}    ;
        illegal_bins invalid_range = {[MAX_aligned_addr+1:$]}        ;
    }

    ARLEN_cp: coverpoint ARLEN iff(ARVALID && ARESETn) {
        bins ARLEN_min_range       = {[0:64]}   ;
        bins ARLEN_mid_range       = {[65:128]} ;
        bins ARLEN_max_range       = {[129:$]}  ; 
    }

    ARSIZE_cp: coverpoint ARSIZE iff(ARVALID && ARESETn) {
        bins ARSIZE_4byte = {2};
        //azwed illegal bins
    }

    ARVALID_cp: coverpoint ARVALID {
        bins valid = {1} ;
        ignore_bins not_valid = {0} ;
    }

    RDATA_cp: coverpoint RDATA iff(ARVALID && ARESETn) {
        bins all_zeros = {0}                                       ;
        bins all_ones  = {{DATA_WIDTH{1'b1}}}                      ;
        bins alternating_pattern[] = { 'h5555_5555, 'hAAAA_AAAA }  ;
        bins trans     = ([1:$] => 0)                              ;
        bins misc      = default                                   ;
    }

    //azwed coverpoint lel resp
    //cross ma been max adderess wel awvalid

WCROSS_LAST_VALID_READY : cross WVALID, WREADY, WLAST
    {
        option.cross_auto_bin_max = 0;
        bins all_high = binsof(WVALID) intersect {1} &&
                        binsof(WREADY) intersect {1} &&
                        binsof(WLAST)  intersect {1};
    }

    WCROSS_VALID_READY_ADDR : cross AWVALID, AWREADY         
    {

        option.cross_auto_bin_max = 0;
        bins all_high = binsof(AWVALID) intersect {1} &&
                        binsof(AWREADY) intersect {1} ;
    }

    WCROSS_BVALID_BREADY    : cross BREADY, BVALID       
    {
        option.cross_auto_bin_max = 0;
        bins all_high = binsof(BREADY) intersect {1} &&
                        binsof(BVALID) intersect {1} ;
    }    

    RCROSS_LAST_VALID_READY : cross ARVALID, ARREADY, RLAST  
    {
        option.cross_auto_bin_max = 0;
        bins all_high = binsof(ARVALID) intersect {1} &&
                        binsof(ARREADY) intersect {1} &&
                        binsof(RLAST)   intersect {1};
    }
    RCROSS_VALID_READY_ADDR : cross ARVALID, ARREADY         
    {
        option.cross_auto_bin_max = 0;
        ignore_bins ARVALID_low = binsof(ARVALID) intersect {0} ;
        ignore_bins ARREADY_low = binsof(ARREADY) intersect {0} ;
        bins all_high = binsof(ARVALID) intersect {1} &&
                        binsof(ARREADY) intersect {1};
    }



    endgroup : ax_cg


    function void display_stimulus(string name, string sentence = "");
        $display("at %0t [%0s]: %0s ARESETn = %0b, AWADDR = %0h, AWLEN = %0d, AWSIZE = %0d, AWVALID = %0b, AWREADY = %0b, WDATA = %0p, WVALID = %0b, WLAST = %0b, BREADY = %0b, ARADDR = %0h, ARLEN = %0d, ARSIZE = %0d, ARVALID = %0b, ARREADY = %0b, RREADY = %0b, RDATA = %0p, RVALID = %0b, RLAST = %0b, BRESP = %0b",
                $time, name, sentence, ARESETn, AWADDR, AWLEN, AWSIZE, AWVALID, AWREADY, WDATA, WVALID, WLAST, BREADY, ARADDR, ARLEN, ARSIZE, ARVALID, ARREADY, RREADY, RDATA, RVALID, RLAST, BRESP);
    endfunction

    function new();
        ax_cg = new()   ;        
    endfunction //new()

    function void post_randomize();
      
    
        
    endfunction
endclass //axi4_pkt
    
endpackage